# permissions for end users to view transporturls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: transporturl-viewer-role
rules:
- apiGroups:
  - rabbitmq.openstack.org
  resources:
  - transporturls
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rabbitmq.openstack.org
  resources:
  - transporturls/status
  verbs:
  - get
