# permissions for end users to edit transporturls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: transporturl-editor-role
rules:
- apiGroups:
  - rabbitmq.openstack.org
  resources:
  - transporturls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rabbitmq.openstack.org
  resources:
  - transporturls/status
  verbs:
  - get
