apiVersion: core.openstack.org/v1beta1
kind: OpenStackControlPlane
metadata:
  name: openstack
spec:
  secret: osp-secret
  storageClass: local-storage
  keystoneTemplate:
    containerImage: quay.io/tripleowallabycentos9/openstack-keystone:current-tripleo
    databaseInstance: openstack
  mariadbTemplate:
    containerImage: quay.io/tripleowallabycentos9/openstack-mariadb:current-tripleo
    storageRequest: 500M
  rabbitmqTemplate:
    replicas: 1
    #resources:
    #  requests:
    #    cpu: 500m
    #    memory: 1Gi
    #  limits:
    #    cpu: 800m
    #    memory: 1Gi
  placementTemplate:
    containerImage: quay.io/tripleowallabycentos9/openstack-placement-api:current-tripleo
  glanceTemplate:
    containerImage: quay.io/tripleowallabycentos9/openstack-glance-api:current-tripleo
    storageClass: ""
    storageRequest: 10G
